### 빅데이터란

- RDBMS(관계형 데이터베이스 관리 시스템)과 같은 전통적 데이터 관리 기법으로 다루기 힘든 데이터
- 기존의 방법이나 도구로는 데이터의 수집이나 저장, 분석 등이 어려운 정형 및 비정형 데이터

### - 빅데이터 처리 및 분석을 위한 기본 프로그래밍 도구

- R, Python ...
- 이중에도 Python을 널리 사용하는 이유는 목적에 따른 다양한 패키지가 개발 및 출시되고 있기 때문
    - Ex. Numpy - 동일한 데이터 타입을 가진 배열 기반의 데이터 처리
    - Pandas - data frame 형태로 데이터를 다룸
    - Scipy - 과학 계산 작업
    - Matplotlib - 데이터 시각화
    - Scikit-Learn 머신러닝

### - 데이터 분석

- 데이터는 다양한 형식으로 존재함
    - Ex. 이미지 데이터 → 2차원 숫자배열(픽셀 밝기)
    - 사운드 데이터 → 1차원 배열(시간대비 강도)
    - 
- (과정)원본 데이터를 숫자 배열로 변환 → 편한 방식으로 연산 적용 → 연산 결과를 다루기 쉬운 형태로 변환
- 숫자 배열을 효율적으로 저장하고 가공하는 것은 빅데이터 분석을 위한 기본적인 절차이다. (Python-Numpy 패키지 이용)

### - 넘파이 (Numerical Python)

- array 단위로 데이터 관리 및 연산 수행

1) 넘파이 패키지 임포트

In [1]:
import numpy as np

In [2]:
data1 = [1, 2, 3, 4, 5]
data2 = [6, 5, 4, 3, 2, 1]

print(data1, data2)

[1, 2, 3, 4, 5] [6, 5, 4, 3, 2, 1]


In [3]:
ar1 = np.array(data1)
ar1

array([1, 2, 3, 4, 5])

In [4]:
ar2 = np.array(data1, dtype='float32')
ar2

array([1., 2., 3., 4., 5.], dtype=float32)

In [5]:
ar3 = np.array([range(i, i + 3) for i in data1])
ar3

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [6]:
ar4 = np.full((3, 5), 3.14)
ar4

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [8]:
ar5 = np.arange(0, 20, 2)
ar5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
ar6 = np.linspace(0, 1, 3)
ar6

array([0. , 0.5, 1. ])

In [10]:
ar7 = np.random.random((3, 3))
ar7

array([[0.80095105, 0.04239105, 0.87370799],
       [0.67513929, 0.53993732, 0.92361801],
       [0.04360665, 0.49505739, 0.59612306]])

In [11]:
ar8 = np.random.randint(0, 100, (3, 3))
ar8

array([[39, 70, 76],
       [87, 34, 65],
       [13,  4, 58]])

In [12]:
ar9 = np.eye(3)
ar9


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
x = np.random.randint(10, size=(3, 4, 5))
x

array([[[7, 7, 1, 2, 2],
        [4, 5, 4, 8, 9],
        [7, 1, 7, 1, 0],
        [7, 5, 8, 7, 7]],

       [[4, 8, 6, 3, 1],
        [1, 4, 8, 7, 7],
        [0, 2, 4, 3, 4],
        [4, 6, 1, 5, 6]],

       [[6, 6, 9, 8, 9],
        [9, 8, 8, 7, 6],
        [3, 2, 4, 7, 1],
        [2, 7, 3, 8, 9]]])

In [15]:
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)


x ndim:  3
x shape:  (3, 4, 5)
x size:  60
